{
 "title": "Kraken",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instances",
    "query": "label_values(up{job=\"kraken\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature & relative humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "kraken_temperature_celsius{instance=~\"$instances\"}",
     "legendFormat": "Celsius {{location}} {{room}}"
    },
    {
     "expr": "kraken_relative_humidity_percent{instance=~\"$instances\"}",
     "legendFormat": "Relative humidity {{location}} {{room}}"
    }
   ]
  },
  {
   "title": "Air pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "kraken_airpressure_hectopascals{instance=~\"$instances\"}",
     "legendFormat": "{{location}} {{room}}"
    }
   ]
  },
  {
   "title": "VOCs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "kraken_voc_ppm{instance=~\"$instances\"}",
     "legendFormat": "VOCs {{location}} {{room}}"
    },
    {
     "expr": "kraken_voc_ppm_balanced{instance=~\"$instances\"}",
     "legendFormat": "VOCs balanced {{location}} {{room}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"kraken\",instance=~\"$instances\"} < 9"
    }
   ]
  },
  {
   "title": "Sättigungsdampfdruck in hPa",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "(6.1078 * 10^((7.5*kraken_temperature_celsius)/(237.3+kraken_temperature_celsius)))"
    }
   ]
  },
  {
   "title": "Dampfdruck in hPa",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": " (kraken_relative_humidity_percent / 100 * (6.1078 * 10^((7.5*kraken_temperature_celsius)/(237.3+kraken_temperature_celsius))))"
    }
   ]
  },
  {
   "title": "Taupunkt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "237.3*log10((kraken_relative_humidity_percent / 100 * (6.1078 * 10^((7.5*kraken_temperature_celsius)/(237.3+kraken_temperature_celsius))))/6.1078) / (7.5 - log10((kraken_relative_humidity_percent / 100 * (6.1078 * 10^((7.5*kraken_temperature_celsius)/(237.3+kraken_temperature_celsius))))/6.1078))"
    }
   ]
  }
 ]
}