{
 "title": "kraken",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "krakens",
    "query": {
     "query": "label_values(kraken_temperature_celsius, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature & relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "kraken_temperature_celsius{instance=~\"$krakens\"}",
     "legendFormat": "Temperature {{instance}}"
    },
    {
     "expr": "kraken_humidity_relative{instance=~\"$krakens\"}",
     "legendFormat": "Relative humidity {{instance}}"
    },
    {
     "expr": "kraken_dew_point_celsius{instance=~\"$krakens\"}",
     "legendFormat": "Dew point {{instance}}"
    }
   ]
  },
  {
   "title": "Air pressure & gas resistance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "expr": "kraken_pressure_pascal{instance=~\"$krakens\"}",
     "legendFormat": "Air pressure {{instance}}"
    },
    {
     "expr": "kraken_gas_resistance_ohm{instance=~\"$krakens\"}",
     "legendFormat": "Gas resistance {{instance}}"
    }
   ]
  },
  {
   "title": "Calculated Altitude (see description)",
   "type": "timeseries",
   "description": "This value is calculated, not measured against a reference like GPS. Unless you compensate for air pressure changes, the altitude will be off. It can be useful in a moving sensor, and of academic interest in a stationary sensor.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "kraken_altitude_meter{instance=~\"$krakens\"}",
     "legendFormat": "Altitude {{instance}}"
    }
   ]
  }
 ]
}